smoke test

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -55,3 +55,13 @@ jobs:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           package: '../GitHubActionBlazorApp'
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
+      # smoke test and check response code 200
+      - name: smoke test
+        run: |
+          RESPONSE= $(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net)
+          if [ $RESPONSE -eq 200 ]; then
+            echo "Smoke test passed"
+          else
+            echo "Smoke test failed"
+            exit 1
+          fi
